name: forscore

# Model configs from trl
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
attn_implementation: flash_attention_2
lora_r: 64
lora_alpha: 64
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- down_proj
- up_proj
- gate_proj

# GRPO trainer configs from trl
# adam_beta1: 0.9
# adam_beta2: 0.99
bf16: true
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5e-6
log_completions: true
logging_first_step: false
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
warmup_ratio: 0.1
max_completion_length: 1536  # 512 + 1536 = 2048 total max
# max_grad_norm: 0.1
max_prompt_length: 512  # FSM problems with DOT notation need more space
max_steps: 5000 # 10000 prompts, 2 prompts per step
num_completions_to_print: 1
num_generations: 4
num_train_epochs: 1
overwrite_output_dir: true
per_device_train_batch_size: 4
report_to:
- wandb
reward_weights: [1.0, 5.0, 1.0]  # format, final_state_correct, token_count
temperature: 0.7
save_steps: 1000
save_strategy: steps
save_total_limit: 10
seed: 42
use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.4
wandb_log_unique_prompts: true
